<h2>Créer un nouvel utilisateur</h2>
<form action="index.php?route=check_create_user" method="post">
    <label for="fisrt_name">prenom :</label>
    <input type="text" id="first_name" name="first_name" required><br><br>
    
    <label for="last_name">nom de famille :</label>
    <input type="text" id="last_name" name="last_name" required><br><br>

    <label for="email">email :</label>
    <input type="email" id="email" name="email" required><br><br>

    <label for="id">id :</label>
    <input type="text" id="id" name="id"><br><br>

    <button type="submit">Créer</button>
</form>