<h2>Créer un nouvel utilisateur</h2>
<form action="index.php?route=check_create_user" method="post">
    <label for="name">Nom :</label>
    <input type="text" id="name" name="name" required><br><br>

    <label for="email">Email :</label>
    <input type="email" id="email" name="email" required><br><br>

    <label for="role">Rôle :</label>
    <input type="text" id="role" name="role"><br><br>

    <button type="submit">Créer</button>
</form>